### ISSUE TITLE
MC 1.12 Update

### ISSUE THREAD

**Issue by mibby** [Siguza/VirtualPack#42] opened 2017-05-22 09:49 UTC
Incoming!  💘

**Comment by mibby** [comment] 2017-06-01 02:31
@Siguza 1.12 is scheduled to come out in 2 days, June 2nd, just a heads up. :)

**Comment by Siguza** [comment] 2017-06-01 20:47
Oh dear. Fun times ahead, I see.

Thanks for the notice. :)

**Comment by mibby** [comment] 2017-06-02 06:09
```
[23:00:23] [Server thread/ERROR]: Error occurred while enabling VirtualPack v2.8.12 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/IChatBaseComponent
	at net.drgnome.virtualpack.util.ConfigProxy.setDefs(ConfigProxy.java:137) ~[?:?]
	at net.drgnome.virtualpack.util.ConfigProxy.<init>(ConfigProxy.java:91) ~[?:?]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.reloadConfig(VPlugin.java:905) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) ~[patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.init(VPlugin.java:87) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onEnable(VPlugin.java:264) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_11_R1.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 19 more
[23:00:23] [Server thread/INFO]: [VirtualPack] Disabling VirtualPack v2.8.12
[23:00:23] [Server thread/ERROR]: Error occurred while disabling VirtualPack v2.8.12 (Is it up to date?)
java.lang.NullPointerException: null
	at net.drgnome.virtualpack.util.Config.string(Config.java:72) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:85) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:80) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onDisable(VPlugin.java:278) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12-pre6.jar:git-Paper-"adab11a1"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by mibby** [comment] 2017-06-09 04:31
Error on official final 1.12 release build.

```
[21:29:11] [Server thread/INFO]: [VirtualPack] Enabling VirtualPack v2.8.12
[21:29:11] [Server thread/ERROR]: Error occurred while enabling VirtualPack v2.8.12 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_11_R1/IChatBaseComponent
	at net.drgnome.virtualpack.util.ConfigProxy.setDefs(ConfigProxy.java:137) ~[?:?]
	at net.drgnome.virtualpack.util.ConfigProxy.<init>(ConfigProxy.java:91) ~[?:?]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.reloadConfig(VPlugin.java:905) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:135) ~[patched_1.12.jar:git-Paper-1106]
	at net.drgnome.virtualpack.util.Config.reload(Config.java:27) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.init(VPlugin.java:87) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onEnable(VPlugin.java:264) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1106]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_11_R1.IChatBaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.12.jar:git-Paper-1106]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 19 more
[21:29:11] [Server thread/INFO]: [VirtualPack] Disabling VirtualPack v2.8.12
[21:29:11] [Server thread/ERROR]: Error occurred while disabling VirtualPack v2.8.12 (Is it up to date?)
java.lang.NullPointerException: null
	at net.drgnome.virtualpack.util.Config.string(Config.java:72) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:85) ~[?:?]
	at net.drgnome.virtualpack.util.Config.bool(Config.java:80) ~[?:?]
	at net.drgnome.virtualpack.VPlugin.onDisable(VPlugin.java:278) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:379) [patched_1.12.jar:git-Paper-1106]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.12.jar:git-Paper-1106]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.12.jar:git-Paper-1106]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

**Comment by jordanwilliams1** [comment] 2017-06-10 07:33
@Siguza Please release an update 😭

**Comment by Siguza** [comment] 2017-06-11 00:04
Jeez, calm down. You're acting like this wasn't open source or something.

I'll have a look at it tomorrow.

**Comment by jordanwilliams1** [comment] 2017-06-11 01:15
@Siguza Thank you 😄

**Comment by Siguza** [comment] 2017-06-11 22:58
Just committed 1.12 support with 1229ef15e96dbaac6db7dcd56406bac7f730be10.  
Everything I tested seemed to be working, please report if I missed anything.

**Comment by mibby** [comment] 2017-06-12 07:00
Will do, thanks! :)

**Comment by mibby** [comment] 2017-07-04 10:23
@Siguza Minor issue someone reported to me. Has this always been a thing to avoid easy item abuse or is it an issue with 1.12?

>  I've noticed recently there's been a slight change with the /uc command. When uncrafting dyes, eg: red dye, you get red tulips - which is pretty cool and all but I realised there's a slight problem with it that's occurred for me.

When using /uc on dyes that have been mixed - I can't get the two primary dyes back and I get a flower instead. For example when I /uc silver / light grey dye it gives me a white tulip instead of 2 bone meal dyes and an ink sac. I find this rather annoying due to the fact that ink sacs are difficult to get in bulk so obtaining the through /uc is one of my only sources and now it's gone.

**Comment by Siguza** [comment] 2017-07-04 12:53
That seems to be due to a change in Minecraft code, as far as I can tell.

The only explicit checks I perform are against enchanted items, and the white- and blacklists. Everything else is simply checked against the list of all crafting recipes which is fetched from `CraftingManager` on startup. The problem is that there may be multiple crafting recipes yielding the same item, but the uncrafter has to choose one set of ingredients to map back to. This has always been done by simply taking the first matching entry. For example, sticks can be crafted from any type of wooden planks, but uncrafting sticks will always yield the same kind of wooden planks (oak, last time I checked). It seems that the recipe for light grey dye using white tulips used to be behind the one using ink sacs and bone meal in the list, but this order has changed now.

I'm not sure whether I _want_ to do something about it. I'm certainly not gonna add checks for any explicit items, ink sacs or otherwise. I guess I _could_ choose the used recipe at random, but that would only add to the complexity and quite frankly, I'd be annoyed to uncraft a stack of sticks and end up with 6 stacks of different wooden planks.

Also, I do have to say farming white tulips and turning them into bone meal and ink sacs does sound like a rather shady practice. _If_ you really need ink sacs in bulk - why not build a couple dozen [squid farms](http://minecraft.gamepedia.com/Tutorials/Squid_farming)?

**Comment by mibby** [comment] 2017-07-05 06:05
I agree with you. I say just keep it as current behavior and not randomize the crafting recipe. It isn't too much of an issue.

**Closed** 2017-10-07 20:13 UTC
